// Package exceltest validates xlsx workbooks generated by the atscale-utils
// generate-excel-from-namespace command using the excelize library as the
// reference parser. Tests cover both positive (valid inputs) and negative
// (edge-case / bad inputs) scenarios.
//
// Run from this directory:
//
//	go test -v ./...
package exceltest

import (
	"archive/zip"
	"bytes"
	"encoding/xml"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"testing"

	excelize "github.com/xuri/excelize/v2"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// ---------------------------------------------------------------------------
// Test cache: generate each fixture once, share across all tests
// ---------------------------------------------------------------------------

// fixtureCache maps nsYAML → *fixtureEntry (sync.Once + result).
// Each unique fixture is generated exactly once even under t.Parallel().
var (
	fixtureCache    sync.Map   // map[string]*fixtureEntry
	fixtureCacheDir string     // package-level temp dir, owned by TestMain
)

type fixtureEntry struct {
	once sync.Once
	path string
}

// TestMain creates the shared temp dir, pre-builds the CLI once, runs the
// suite, then cleans up.  Building once here prevents concurrent npm-run-build
// invocations (one per parallel test) from corrupting the dist/ directory.
func TestMain(m *testing.M) {
	var err error
	fixtureCacheDir, err = os.MkdirTemp("", "exceltest-cache-*")
	if err != nil {
		panic(err)
	}

	// Build once up-front; individual CLI invocations will skip the build step.
	buildCmd := exec.Command("npm", "run", "build")
	buildCmd.Dir = projectRoot
	if out, err := buildCmd.CombinedOutput(); err != nil {
		panic(fmt.Sprintf("pre-test npm run build failed: %v\n%s", err, out))
	}
	// Signal to atscale-utils that the build is already up-to-date.
	os.Setenv("ATSCALE_SKIP_BUILD", "1")

	code := m.Run()
	_ = os.RemoveAll(fixtureCacheDir)
	os.Exit(code)
}

// ---------------------------------------------------------------------------
// Fixture namespaces
// ---------------------------------------------------------------------------

const nsValid = `
worksheets:
  revenue_by_month:
    title: "Revenue by Month"
    model: "Telemetry"
    graphType: bar
    measures:
      - m_query_id_count
    xAxis: query_hour

  total_cost:
    title: "Total Queries"
    model: "Telemetry"
    graphType: text
    measures:
      - m_query_id_count

dashboards:
  Test Dashboard:
    tiles:
      - worksheet: revenue_by_month
      - worksheet: total_cost
`

// nsMultipleTilesSameXY — two tiles with default x=0,y=0 to exercise
// the x-collision deduplication fix.
const nsMultipleTilesSameXY = `
worksheets:
  ws_a:
    title: "Widget A"
    model: "Telemetry"
    graphType: bar
    measures:
      - m_query_id_count
    xAxis: query_hour

  ws_b:
    title: "Widget B"
    model: "Telemetry"
    graphType: text
    measures:
      - m_query_id_count

  ws_c:
    title: "Widget C"
    model: "Telemetry"
    graphType: bar
    measures:
      - m_query_id_count
    xAxis: query_hour

dashboards:
  Multi Tile:
    tiles:
      - worksheet: ws_a
      - worksheet: ws_b
      - worksheet: ws_c
`

// nsNoDashboards — valid worksheets but no dashboards section.
const nsNoDashboards = `
worksheets:
  orphan:
    title: "Orphan"
    model: "Telemetry"
    graphType: text
    measures:
      - m_query_id_count

dashboards: {}
`

// nsNoMeasures — worksheet with empty measures list.
const nsNoMeasures = `
worksheets:
  empty_measures:
    title: "No Measures"
    model: "Telemetry"
    graphType: text
    measures: []

dashboards:
  Empty Dashboard:
    tiles:
      - worksheet: empty_measures
`

// nsUnknownModel — tile references a model that does not exist in model.yaml.
const nsUnknownModel = `
worksheets:
  ghost:
    title: "Ghost Tile"
    model: "NonExistentModel"
    graphType: text
    measures:
      - m_query_id_count

dashboards:
  Ghost Dashboard:
    tiles:
      - worksheet: ghost
`

// nsUnknownGraphType — unrecognised graphType should default to bar.
const nsUnknownGraphType = `
worksheets:
  odd_chart:
    title: "Odd Chart"
    model: "Telemetry"
    graphType: radar
    measures:
      - m_query_id_count
    xAxis: query_hour

dashboards:
  Odd Dashboard:
    tiles:
      - worksheet: odd_chart
`

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

// projectRoot is the absolute path to the atscale/template directory.
// Go tests run with CWD = the package directory (test/), so "../" is the root.
var projectRoot = func() string {
	abs, err := filepath.Abs("..")
	if err != nil {
		panic(err)
	}
	return abs
}()

// generate returns the path to a cached xlsx generated from nsYAML.
// Each unique nsYAML string is generated exactly once per test run via
// sync.Once, so concurrent t.Parallel() tests never race on generation.
func generate(t *testing.T, nsYAML string) string {
	t.Helper()

	// Get or create the once-entry for this fixture.
	entry := &fixtureEntry{}
	actual, _ := fixtureCache.LoadOrStore(nsYAML, entry)
	entry = actual.(*fixtureEntry)

	// Generate exactly once; other goroutines block here until done.
	entry.once.Do(func() {
		nsFile, err := os.CreateTemp(fixtureCacheDir, "ns-*.yaml")
		if err != nil {
			panic("create temp namespace file: " + err.Error())
		}
		if _, err = nsFile.WriteString(nsYAML); err != nil {
			panic(err.Error())
		}
		if err = nsFile.Close(); err != nil {
			panic(err.Error())
		}

		out := filepath.Join(fixtureCacheDir, filepath.Base(nsFile.Name())+".xlsx")
		cli := filepath.Join(projectRoot, "atscale-utils")

		cmd := exec.Command(
			cli,
			"generate-excel-from-namespace",
			"--namespace-file", nsFile.Name(),
			"--model-file", filepath.Join(projectRoot, "example", "model.yaml"),
			"--connection-file", filepath.Join(projectRoot, "example", "connections.yaml"),
			"--connection-name", "ats_connection",
			"--target-file", out,
		)
		cmd.Dir = projectRoot

		if output, err := cmd.CombinedOutput(); err != nil {
			panic(fmt.Sprintf("generate-excel-from-namespace failed: %v\n%s", err, output))
		}
		entry.path = out
	})

	if entry.path == "" {
		t.Fatal("fixture generation failed (see panic output above)")
	}
	return entry.path
}

// generateExpectError runs the CLI with the given namespace YAML and asserts that
// it exits with a non-zero status. Returns the combined stderr+stdout output so
// callers can assert on the error message.
func generateExpectError(t *testing.T, nsYAML string) string {
	t.Helper()

	nsFile, err := os.CreateTemp(t.TempDir(), "ns-*.yaml")
	require.NoError(t, err)
	_, err = nsFile.WriteString(nsYAML)
	require.NoError(t, err)
	require.NoError(t, nsFile.Close())

	out := filepath.Join(t.TempDir(), "out.xlsx")
	cli := filepath.Join(projectRoot, "atscale-utils")

	cmd := exec.Command(
		cli,
		"generate-excel-from-namespace",
		"--namespace-file", nsFile.Name(),
		"--model-file", filepath.Join(projectRoot, "example", "model.yaml"),
		"--connection-file", filepath.Join(projectRoot, "example", "connections.yaml"),
		"--connection-name", "ats_connection",
		"--target-file", out,
	)
	cmd.Dir = projectRoot

	combined, err := cmd.CombinedOutput()
	require.Error(t, err, "CLI should have exited with a non-zero status for this namespace")
	assert.NoFileExists(t, out, "no xlsx file should be created when generation fails")
	return string(combined)
}

// openXlsx opens an xlsx file with excelize, failing the test on error.
func openXlsx(t *testing.T, path string) *excelize.File {
	t.Helper()
	f, err := excelize.OpenFile(path)
	require.NoError(t, err, "excelize.OpenFile(%s)", filepath.Base(path))
	t.Cleanup(func() { _ = f.Close() })
	return f
}

// rawZipEntry reads the bytes of a named entry from a zip archive.
func rawZipEntry(t *testing.T, xlsxPath, entryName string) []byte {
	t.Helper()
	data, err := os.ReadFile(xlsxPath)
	require.NoError(t, err)
	r, err := zip.NewReader(bytes.NewReader(data), int64(len(data)))
	require.NoError(t, err)
	for _, f := range r.File {
		if f.Name == entryName {
			rc, err := f.Open()
			require.NoError(t, err)
			defer rc.Close()
			var buf bytes.Buffer
			_, err = buf.ReadFrom(rc)
			require.NoError(t, err)
			return buf.Bytes()
		}
	}
	return nil
}

// zipEntries returns all file names in a zip archive.
func zipEntries(t *testing.T, xlsxPath string) []string {
	t.Helper()
	data, err := os.ReadFile(xlsxPath)
	require.NoError(t, err)
	r, err := zip.NewReader(bytes.NewReader(data), int64(len(data)))
	require.NoError(t, err)
	names := make([]string, 0, len(r.File))
	for _, f := range r.File {
		if !f.FileInfo().IsDir() {
			names = append(names, f.Name)
		}
	}
	return names
}

// ---------------------------------------------------------------------------
// Raw XML types for assertions that go beyond excelize's public API
// ---------------------------------------------------------------------------

type xmlContentTypes struct {
	XMLName   xml.Name           `xml:"Types"`
	Overrides []xmlOverride      `xml:"Override"`
}
type xmlOverride struct {
	PartName    string `xml:"PartName,attr"`
	ContentType string `xml:"ContentType,attr"`
}

type xmlPivotTableDef struct {
	XMLName  xml.Name    `xml:"pivotTableDefinition"`
	Name     string      `xml:"name,attr"`
	Location xmlLocation `xml:"location"`
}
type xmlLocation struct {
	Ref            string `xml:"ref,attr"`
	FirstHeaderRow int    `xml:"firstHeaderRow,attr"`
	FirstDataRow   int    `xml:"firstDataRow,attr"`
}

type xmlDrawingWsDr struct {
	XMLName       xml.Name        `xml:"wsDr"`
	TwoCellAnchors []xmlTwoCellAnchor `xml:"twoCellAnchor"`
}
type xmlTwoCellAnchor struct {
	GraphicFrame *xmlGraphicFrame `xml:"graphicFrame"`
}
type xmlGraphicFrame struct {
	NvPr *xmlNvGraphicFramePr `xml:"nvGraphicFramePr"`
}
type xmlNvGraphicFramePr struct {
	CNvPr            *struct{ ID int `xml:"id,attr"` } `xml:"cNvPr"`
	CnvGraphicFramePr *struct{} `xml:"cNvGraphicFramePr"`
	NvPr             *struct{} `xml:"nvPr"`
}

type xmlPivotCacheDef struct {
	XMLName          xml.Name              `xml:"pivotCacheDefinition"`
	SaveData         string                `xml:"saveData,attr"`
	CreatedVersion   string                `xml:"createdVersion,attr"`
	RefreshedVersion string                `xml:"refreshedVersion,attr"`
	CacheHierarchies *xmlCacheHierarchies  `xml:"cacheHierarchies"`
}
type xmlCacheHierarchies struct {
	Count int `xml:"count,attr"`
}

// ---------------------------------------------------------------------------
// POSITIVE TESTS — valid namespace_test.yaml
// ---------------------------------------------------------------------------

// TestPositive_WorkbookOpenable verifies excelize can parse the file without error.
func TestPositive_WorkbookOpenable(t *testing.T) {
	t.Parallel()
	path := generate(t, nsValid)
	openXlsx(t, path) // fails test on error
}

// TestPositive_SheetNames verifies the correct sheets are present: one dashboard
// sheet and the hidden _Connections sheet. No hidden per-worksheet data sheets.
func TestPositive_SheetNames(t *testing.T) {
	t.Parallel()
	path := generate(t, nsValid)
	f := openXlsx(t, path)

	sheets := f.GetSheetList()
	assert.Contains(t, sheets, "Test Dashboard", "dashboard sheet")
	assert.Contains(t, sheets, "_Connections", "connections sheet")
	assert.NotContains(t, sheets, "revenue_by_month", "no separate data sheet for revenue_by_month")
	assert.NotContains(t, sheets, "total_cost", "no separate data sheet for total_cost")
}

// TestPositive_DataSheetsHidden verifies no worksheet-named data sheets exist.
// CUBE formula data sections now live in the dashboard sheet itself.
func TestPositive_DataSheetsHidden(t *testing.T) {
	t.Parallel()
	path := generate(t, nsValid)
	f := openXlsx(t, path)

	sheets := f.GetSheetList()
	for _, name := range []string{"revenue_by_month", "total_cost"} {
		assert.NotContains(t, sheets, name,
			"worksheet-named data sheet %q should not exist; data lives in dashboard sheet", name)
	}
}

// TestPositive_DashboardVisible verifies the dashboard sheet is visible.
func TestPositive_DashboardVisible(t *testing.T) {
	t.Parallel()
	path := generate(t, nsValid)
	f := openXlsx(t, path)

	visible, err := f.GetSheetVisible("Test Dashboard")
	require.NoError(t, err)
	assert.True(t, visible, "dashboard sheet should be visible")
}

// TestPositive_DataSheetHeaders verifies row 1 of each data section on the
// dashboard sheet has the expected column headers.
//
// Data sections are placed starting at column X (= bannerEndCol+3 = 24) for
// the default hSegments=2 layout:
//   revenue_by_month: X1=query_hour, Y1=m_query_id_count (2 cols)
//   total_cost:       Z1=m_query_id_count               (1 col, no xAxis)
func TestPositive_DataSheetHeaders(t *testing.T) {
	t.Parallel()
	path := generate(t, nsValid)
	f := openXlsx(t, path)

	// revenue_by_month data section starts at column X (24)
	x1, err := f.GetCellValue("Test Dashboard", "X1")
	require.NoError(t, err)
	assert.Equal(t, "query_hour", x1, "Test Dashboard X1 should be xAxis header for revenue_by_month")

	y1, err := f.GetCellValue("Test Dashboard", "Y1")
	require.NoError(t, err)
	assert.Equal(t, "m_query_id_count", y1, "Test Dashboard Y1 should be measure header for revenue_by_month")

	// total_cost data section starts at column Z (26)
	z1, err := f.GetCellValue("Test Dashboard", "Z1")
	require.NoError(t, err)
	assert.Equal(t, "m_query_id_count", z1, "Test Dashboard Z1 should be measure header for total_cost")
}

// TestPositive_CubeFormulasInDataSheet verifies CUBE function formulas are
// written to rows 2–11 of the data section on the dashboard sheet.
//
// Data sections for nsValid (hSegments=2):
//   revenue_by_month: X=category (CUBERANKEDMEMBER), Y=measure (CUBEVALUE)
//   total_cost:       Z=grand total (CUBEVALUE, no dimension)
func TestPositive_CubeFormulasInDataSheet(t *testing.T) {
	t.Parallel()
	path := generate(t, nsValid)
	f := openXlsx(t, path)

	for row := 2; row <= 11; row++ {
		cellX := fmt.Sprintf("X%d", row)
		cellY := fmt.Sprintf("Y%d", row)

		fX, err := f.GetCellFormula("Test Dashboard", cellX)
		require.NoError(t, err, "GetCellFormula Test Dashboard %s", cellX)
		assert.True(t, strings.HasPrefix(fX, "CUBERANKEDMEMBER("),
			"Test Dashboard %s should be CUBERANKEDMEMBER, got: %s", cellX, fX)

		fY, err := f.GetCellFormula("Test Dashboard", cellY)
		require.NoError(t, err, "GetCellFormula Test Dashboard %s", cellY)
		assert.True(t, strings.HasPrefix(fY, "CUBEVALUE("),
			"Test Dashboard %s should be CUBEVALUE, got: %s", cellY, fY)
	}

	// total_cost: only Z2 has a CUBEVALUE (grand total, no dimension)
	fZ2, err := f.GetCellFormula("Test Dashboard", "Z2")
	require.NoError(t, err)
	assert.True(t, strings.HasPrefix(fZ2, "CUBEVALUE("),
		"Test Dashboard Z2 should be CUBEVALUE grand total, got: %s", fZ2)
}

// TestPositive_CubeFormulasReferenceCorrectConnection verifies CUBE formulas
// use the connection name from --connection-name.
// Data sections for nsValid (hSegments=2): revenue_by_month at X2, total_cost at Z2.
func TestPositive_CubeFormulasReferenceCorrectConnection(t *testing.T) {
	t.Parallel()
	path := generate(t, nsValid)
	f := openXlsx(t, path)

	formula, err := f.GetCellFormula("Test Dashboard", "X2")
	require.NoError(t, err)
	assert.Contains(t, formula, `"ats_connection"`,
		"CUBERANKEDMEMBER should reference connection name ats_connection")

	formula2, err := f.GetCellFormula("Test Dashboard", "Z2")
	require.NoError(t, err)
	assert.Contains(t, formula2, `"ats_connection"`,
		"CUBEVALUE should reference connection name ats_connection")
}

// TestPositive_PivotTableAtRow15 verifies the pivot table is anchored at row
// 15 (below the CUBE data area), not at row 1 where it would conflict.
func TestPositive_PivotTableAtRow15(t *testing.T) {
	t.Parallel()
	path := generate(t, nsValid)
	entries := zipEntries(t, path)

	var pivotTableFiles []string
	for _, e := range entries {
		if strings.HasPrefix(e, "xl/pivotTables/pivotTable") {
			pivotTableFiles = append(pivotTableFiles, e)
		}
	}
	require.NotEmpty(t, pivotTableFiles, "expected at least one pivot table")

	for _, ptFile := range pivotTableFiles {
		raw := rawZipEntry(t, path, ptFile)
		require.NotNil(t, raw, "pivot table file %s missing from zip", ptFile)

		var def xmlPivotTableDef
		require.NoError(t, xml.Unmarshal(raw, &def), "parse %s", ptFile)

		// Location ref should start with "A15" (or another anchor in row 15+).
		assert.True(t, strings.HasPrefix(def.Location.Ref, "A15"),
			"%s: pivot table should be anchored at row 15, got ref=%q", ptFile, def.Location.Ref)
	}
}

// TestPositive_PivotCacheIsOLAP verifies pivot cache definitions are
// configured as OLAP (saveData="0", createdVersion="8").
func TestPositive_PivotCacheIsOLAP(t *testing.T) {
	t.Parallel()
	path := generate(t, nsValid)
	entries := zipEntries(t, path)

	var cacheFiles []string
	for _, e := range entries {
		if strings.HasPrefix(e, "xl/pivotCache/pivotCacheDefinition") {
			cacheFiles = append(cacheFiles, e)
		}
	}
	require.NotEmpty(t, cacheFiles, "expected at least one pivot cache definition")

	for _, cf := range cacheFiles {
		raw := rawZipEntry(t, path, cf)
		require.NotNil(t, raw)

		var def xmlPivotCacheDef
		require.NoError(t, xml.Unmarshal(raw, &def), "parse %s", cf)

		assert.Equal(t, "0", def.SaveData,
			"%s: OLAP cache must have saveData=\"0\"", cf)
		assert.Equal(t, "8", def.CreatedVersion,
			"%s: cache must have createdVersion=\"8\" for Excel 2016+", cf)
		assert.Equal(t, "8", def.RefreshedVersion,
			"%s: cache must have refreshedVersion=\"8\"", cf)
		assert.NotNil(t, def.CacheHierarchies,
			"%s: OLAP cache must include cacheHierarchies", cf)
		assert.Greater(t, def.CacheHierarchies.Count, 0,
			"%s: cacheHierarchies count must be > 0", cf)
	}
}

// TestPositive_NoContentTypeDuplicates verifies [Content_Types].xml has no
// duplicate PartName entries (the bug that caused "completely corrupt" errors).
func TestPositive_NoContentTypeDuplicates(t *testing.T) {
	t.Parallel()
	path := generate(t, nsValid)
	raw := rawZipEntry(t, path, "[Content_Types].xml")
	require.NotNil(t, raw, "[Content_Types].xml missing")

	var ct xmlContentTypes
	require.NoError(t, xml.Unmarshal(raw, &ct))

	seen := make(map[string]int)
	for _, o := range ct.Overrides {
		seen[o.PartName]++
	}
	for partName, count := range seen {
		assert.Equal(t, 1, count,
			"[Content_Types].xml has %d entries for PartName %q (want 1)", count, partName)
	}
}

// TestPositive_ContentTypesIncludeRequiredParts checks that pivot tables,
// pivot caches, charts, drawings, and connections are registered.
func TestPositive_ContentTypesIncludeRequiredParts(t *testing.T) {
	t.Parallel()
	path := generate(t, nsValid)
	raw := rawZipEntry(t, path, "[Content_Types].xml")
	require.NotNil(t, raw)

	rawStr := string(raw)
	required := []string{
		"pivotCacheDefinition+xml",
		"pivotTable+xml",
		"connections+xml",
		"chart+xml",
		"drawing+xml",
	}
	for _, ct := range required {
		assert.Contains(t, rawStr, ct, "content types should register %s", ct)
	}
}

// TestPositive_ConnectionsXmlPresent verifies the OLAP connections file exists
// with the correct connection name and OLAP type.
func TestPositive_ConnectionsXmlPresent(t *testing.T) {
	t.Parallel()
	path := generate(t, nsValid)
	raw := rawZipEntry(t, path, "xl/connections.xml")
	require.NotNil(t, raw, "xl/connections.xml must be present")

	content := string(raw)
	assert.Contains(t, content, `name="ats_connection"`,
		"connections.xml must reference the connection name")
	assert.Contains(t, content, `type="5"`,
		"connections.xml must use OLAP connection type=5")
}

// TestPositive_DrawingHasNvPr verifies the drawing XML includes the required
// <xdr:nvPr/> element, which was the cause of the "Repaired Records: Drawing"
// error in earlier versions.
func TestPositive_DrawingHasNvPr(t *testing.T) {
	t.Parallel()
	path := generate(t, nsValid)
	entries := zipEntries(t, path)

	var drawingFiles []string
	for _, e := range entries {
		if strings.HasPrefix(e, "xl/drawings/drawing") && !strings.Contains(e, "_rels") {
			drawingFiles = append(drawingFiles, e)
		}
	}
	require.NotEmpty(t, drawingFiles, "expected at least one drawing file")

	for _, df := range drawingFiles {
		raw := rawZipEntry(t, path, df)
		require.NotNil(t, raw)
		assert.Contains(t, string(raw), "<xdr:nvPr/>",
			"%s must include <xdr:nvPr/> in nvGraphicFramePr", df)
	}
}

// TestPositive_DrawingAnchorsOnDashboardOnly verifies drawings are attached
// only to dashboard sheets (not data sheets).
func TestPositive_DrawingAnchorsOnDashboardOnly(t *testing.T) {
	t.Parallel()
	path := generate(t, nsValid)
	f := openXlsx(t, path)
	entries := zipEntries(t, path)

	// Find which sheet numbers have drawing relationships.
	sheetsWithDrawings := make(map[string]bool)
	for _, e := range entries {
		if !strings.HasPrefix(e, "xl/worksheets/_rels/") {
			continue
		}
		raw := rawZipEntry(t, path, e)
		if strings.Contains(string(raw), "/relationships/drawing") {
			// e = "xl/worksheets/_rels/sheetN.xml.rels" → sheet name via workbook
			num := strings.TrimSuffix(strings.TrimPrefix(e, "xl/worksheets/_rels/sheet"), ".xml.rels")
			_ = num
			sheetsWithDrawings[e] = true
		}
	}

	// Every sheet with a drawing must be a visible (dashboard) sheet.
	sheets := f.GetSheetList()
	for _, sheet := range sheets {
		visible, _ := f.GetSheetVisible(sheet)
		_ = visible
	}

	// The simplest assertion: only one drawing file should exist (one dashboard).
	drawingCount := 0
	for _, e := range entries {
		if strings.HasPrefix(e, "xl/drawings/drawing") && !strings.Contains(e, "_rels") {
			drawingCount++
		}
	}
	assert.Equal(t, 1, drawingCount,
		"nsValid has 1 dashboard so should produce exactly 1 drawing file")
}

// TestPositive_PivotCacheHasNoPivotCacheRecords verifies no pivotCacheRecords
// files exist — OLAP caches with saveData="0" must not have them.
func TestPositive_PivotCacheHasNoPivotCacheRecords(t *testing.T) {
	t.Parallel()
	path := generate(t, nsValid)
	for _, e := range zipEntries(t, path) {
		assert.False(t, strings.Contains(e, "pivotCacheRecords"),
			"found unexpected pivotCacheRecords file: %s", e)
	}
}

// TestPositive_WorkbookRelsHasPivotCacheAndConnection verifies workbook.xml.rels
// registers all pivot caches and the connections.xml.
func TestPositive_WorkbookRelsHasPivotCacheAndConnection(t *testing.T) {
	t.Parallel()
	path := generate(t, nsValid)
	raw := rawZipEntry(t, path, "xl/_rels/workbook.xml.rels")
	require.NotNil(t, raw)

	content := string(raw)
	assert.Contains(t, content, "pivotCacheDefinition",
		"workbook.xml.rels must reference pivot cache definitions")
	assert.Contains(t, content, "connections.xml",
		"workbook.xml.rels must reference connections.xml")
}

// TestPositive_MultipleCollidingTilesNoMergeCellError verifies that two tiles
// with the same default x=0 position (the common case when x is unspecified)
// are placed in separate columns without a merge-cell collision error.
func TestPositive_MultipleCollidingTilesNoMergeCellError(t *testing.T) {
	t.Parallel()
	// This test would previously fail with "Cannot merge already merged cells"
	// before the x-position deduplication fix.
	path := generate(t, nsMultipleTilesSameXY) // must not panic/error
	f := openXlsx(t, path)

	sheets := f.GetSheetList()
	assert.Contains(t, sheets, "Multi Tile", "dashboard sheet should be created")
	assert.NotContains(t, sheets, "ws_a", "no separate data sheet for ws_a")
	assert.NotContains(t, sheets, "ws_b", "no separate data sheet for ws_b")
	assert.NotContains(t, sheets, "ws_c", "no separate data sheet for ws_c")

	// Merge cells on the dashboard should all be non-overlapping.
	merges, err := f.GetMergeCells("Multi Tile")
	require.NoError(t, err)
	// Check no two merge ranges share the same top-left cell.
	topLeft := make(map[string]bool)
	for _, m := range merges {
		tl := m.GetStartAxis()
		assert.False(t, topLeft[tl],
			"duplicate merge top-left cell %s (tiles are colliding)", tl)
		topLeft[tl] = true
	}
}

// ---------------------------------------------------------------------------
// NEGATIVE TESTS — edge cases and invalid inputs
// ---------------------------------------------------------------------------

// TestNegative_NoDashboards verifies that a namespace with no dashboard tiles
// (no tile references any worksheet) returns an error and produces no file.
// Without dashboard tiles there are no data passes, so no OLAP pivot table
// can be generated.
func TestNegative_NoDashboards(t *testing.T) {
	t.Parallel()
	output := generateExpectError(t, nsNoDashboards)
	assert.Contains(t, output, "No OLAP pivot table could be generated",
		"error message should explain why generation failed")
}

// TestNegative_NoMeasures verifies that a tile with no measures is handled
// gracefully: no chart is generated (0 series would be invalid OOXML), the
// workbook still opens, and no chart XML files are present.
func TestNegative_NoMeasures(t *testing.T) {
	t.Parallel()
	path := generate(t, nsNoMeasures)
	openXlsx(t, path) // must open without error

	entries := zipEntries(t, path)
	for _, e := range entries {
		assert.False(t, strings.HasPrefix(e, "xl/charts/chart"),
			"no chart should be generated when measures list is empty, found: %s", e)
	}
}

// TestNegative_UnknownModel verifies that referencing a non-existent model
// causes the CLI to exit with an error and produce no output file.
func TestNegative_UnknownModel(t *testing.T) {
	t.Parallel()
	output := generateExpectError(t, nsUnknownModel)
	assert.Contains(t, output, "NonExistentModel",
		"error message should name the missing model")
	assert.Contains(t, output, "not found in model file",
		"error message should explain the cause")
}

// TestNegative_UnknownGraphTypeDefaultsToBarChart verifies that an
// unrecognised graphType (e.g. "radar") falls back to bar chart in the
// generated chart XML.
func TestNegative_UnknownGraphTypeDefaultsToBarChart(t *testing.T) {
	t.Parallel()
	path := generate(t, nsUnknownGraphType)
	entries := zipEntries(t, path)

	var chartFiles []string
	for _, e := range entries {
		if strings.HasPrefix(e, "xl/charts/chart") {
			chartFiles = append(chartFiles, e)
		}
	}
	require.NotEmpty(t, chartFiles, "a chart should be generated for radar graphType")

	for _, cf := range chartFiles {
		raw := rawZipEntry(t, path, cf)
		// buildChartXml defaults to barChart for unrecognised types.
		assert.Contains(t, string(raw), "<c:barChart>",
			"%s: unrecognised graphType should produce barChart", cf)
	}
}

// TestNegative_ChartXmlHasValidSeriesForSingleMeasure verifies a chart with
// one measure + one dimension produces exactly one <c:ser> element.
func TestNegative_ChartXmlHasValidSeriesForSingleMeasure(t *testing.T) {
	t.Parallel()
	path := generate(t, nsValid)
	entries := zipEntries(t, path)

	for _, e := range entries {
		if !strings.HasPrefix(e, "xl/charts/chart") {
			continue
		}
		raw := rawZipEntry(t, path, e)
		content := string(raw)

		// Count <c:ser> elements.
		serCount := strings.Count(content, "<c:ser>")
		assert.Greater(t, serCount, 0, "%s: chart must have at least one series", e)

		// Each series must have a value reference.
		assert.Contains(t, content, "<c:val>",
			"%s: each series must have a value range reference", e)
	}
}

// TestNegative_PivotTableNoFieldsPlaced verifies that pivot table XML does NOT
// include rowFields/dataFields (which Excel would strip for OLAP saveData="0"
// and cause a "Removed Feature" repair message).
func TestNegative_PivotTableNoFieldsPlaced(t *testing.T) {
	t.Parallel()
	path := generate(t, nsValid)
	entries := zipEntries(t, path)

	for _, e := range entries {
		if !strings.HasPrefix(e, "xl/pivotTables/pivotTable") {
			continue
		}
		raw := rawZipEntry(t, path, e)
		content := string(raw)
		assert.NotContains(t, content, "<rowFields",
			"%s: pivot table must not contain rowFields (OLAP saveData=0 strips them)", e)
		assert.NotContains(t, content, "<dataFields",
			"%s: pivot table must not contain dataFields (OLAP saveData=0 strips them)", e)
	}
}
