/**
 * Types for operations.manifest.json (generated by the ps-utils repo's
 * generate-extension-manifest script) plus a loader.
 *
 * Keep these types in sync with src/scripts/generate-extension-manifest.ts.
 */
import * as fs from "fs";
import * as path from "path";

export type ParamRole = "input-file" | "output-file" | "input-dir" | "output-dir" | "scalar";
export type ParamType = "string" | "number" | "boolean";

export interface ManifestParam {
  name: string;
  description: string;
  type: ParamType;
  role: ParamRole;
  required: boolean;
  default: string | number | boolean | null;
}

export interface ManifestOperation {
  description: string;
  group: string;
  contexts: ("file" | "folder")[];
  targetParam: { file?: string; folder?: string };
  params: ManifestParam[];
}

export interface Manifest {
  cliPackage: string;
  cliBin: string;
  settingsParams: Record<string, string>;
  generalGroupName: string;
  groups: { name: string; operations: string[] }[];
  operations: Record<string, ManifestOperation>;
}

/** Load the manifest bundled alongside the compiled extension (../media). */
export function loadManifest(extensionPath: string): Manifest {
  const file = path.join(extensionPath, "media", "operations.manifest.json");
  return JSON.parse(fs.readFileSync(file, "utf8")) as Manifest;
}

export function isFileRole(role: ParamRole): boolean {
  return role === "input-file" || role === "output-file";
}

export function isDirRole(role: ParamRole): boolean {
  return role === "input-dir" || role === "output-dir";
}
