/**
 * SML editing support: associates each SML YAML file with the right JSON Schema so
 * the editor offers completion, hover documentation and validation, and provides
 * the per-project on/off switch surfaced in the PS-Utils Explorer menu.
 *
 * ## Why this goes through redhat.vscode-yaml
 *
 * VS Code core has no YAML schema validation. Both mechanisms for supplying one —
 * the `yamlValidation` contribution point and the `registerContributor` API — belong
 * to the redhat.vscode-yaml extension, so nothing here works without it. It is
 * treated as a *soft* dependency: most PS-Utils users only want the operations
 * context menu, and an `extensionDependencies` entry would force-install a second
 * extension on all of them.
 *
 * ## Why a contributor rather than filename globs alone
 *
 * SML filenames are arbitrary: what determines a file's type is the `object_type`
 * key *inside* it. Globs cannot see that, and `models/` holds both `model` and
 * `composite_model` files. `registerContributor` is resolved per document, so the
 * schema can be chosen by reading `object_type` — and it outranks `yaml.schemas`
 * and `yamlValidation` in the YAML extension's resolution order. The static
 * `yamlValidation` globs in package.json remain as the path that works for files
 * matching the conventional layout.
 *
 * ## Ordering rule
 *
 * Commands and context keys are registered **before** any filesystem work, and
 * nothing below that point may return early past them. A menu item whose command
 * was never registered appears to do nothing when clicked, so the switch must not
 * depend on schema loading having succeeded.
 *
 * ## What the per-project switch does and does not cover
 *
 * `psUtils.smlEnabled` is written to **workspace** scope, so SML support is
 * per-project. It gates schema association, validation, hover, completion and the
 * install prompt.
 *
 * It cannot gate the **syntax highlighting**. That comes from a TextMate injection
 * declared in package.json's `contributes.grammars`, which the editor resolves
 * statically at extension load; there is no API to register or unregister a grammar
 * injection at runtime, and no `when` clause on the contribution point. To switch it
 * off for one project, disable the whole extension there via
 * **Extensions: Disable (Workspace)**.
 */
import * as vscode from "vscode";
import * as fs from "fs";
import * as path from "path";
import { registerUnknownKeyDiagnostics } from "./sml-unknown-keys";
import { Allowlist } from "./sml-unknown-keys-core";
import type { JsonSchema, KnownUndocumented } from "./sml-unknown-keys-core";

const YAML_EXTENSION_ID = "redhat.vscode-yaml";
const SCHEME = "sml";
const CONFIG_SECTION = "psUtils";
/**
 * Single-segment key, matching every other setting this extension declares
 * (`rememberParameters`, `connectionFile`, …).
 *
 * It was briefly `sml.enabled`, which VS Code silently declines to register: the
 * three-segment id implies an intermediate `psUtils.sml` object that is never
 * declared. The failure mode is nastier than a plain error, because reads and writes
 * disagree — `get("sml.enabled", true)` happily returns the *default* for an
 * unregistered key, so the menu rendered the enabled state correctly, while
 * `update()` validates against the registry and threw "not a registered
 * configuration". Keep this flat.
 */
const ENABLED_SETTING = "smlEnabled";
const FULL_SETTING = `${CONFIG_SECTION}.${ENABLED_SETTING}`;
const PROMPT_DISMISSED_KEY = "psUtils.sml.yamlPromptDismissed";

/** Context keys backing the `when` clauses generated by generate-extension-contributes.ts. */
const CTX_YAML_INSTALLED = "psUtils.yamlExtensionInstalled";
const CTX_SML_ENABLED = "psUtils.smlEnabled";

/** Only the first part of a file is scanned for the `object_type` discriminator. */
const SNIFF_BYTES = 8192;

interface SchemaIndexEntry {
  schema: string;
  directory?: string;
}

interface SchemaIndex {
  objectTypes: Record<string, SchemaIndexEntry>;
  /**
   * Keys ps-utils emits that the specification does not document, from the
   * generator's `KNOWN_UNDOCUMENTED` table. The unknown-key linter allowlists
   * them so a known spec gap does not warn on every file that contains it.
   */
  knownUndocumented?: KnownUndocumented[];
}

/** The subset of redhat.vscode-yaml's API this extension uses. */
interface YamlExtensionApi {
  registerContributor(
    schemaId: string,
    requestSchemaUri: (resource: string) => string | undefined,
    requestSchemaContent: (uri: string) => string | undefined,
  ): boolean;
}

/** `object_type: dimension`, tolerating quotes and trailing comments. */
const OBJECT_TYPE = /^object_type\s*:\s*["']?([A-Za-z_][A-Za-z0-9_]*)["']?/m;

/**
 * Diagnostics channel. The SML switch is otherwise invisible when it misbehaves —
 * a failed settings write or an unregistered command both just look like a menu
 * item that does nothing — so every step of it is logged here.
 */
let log: vscode.LogOutputChannel | undefined;

const isEnabled = (): boolean =>
  vscode.workspace.getConfiguration(CONFIG_SECTION).get<boolean>(ENABLED_SETTING, true);

const yamlExtension = (): vscode.Extension<YamlExtensionApi> | undefined =>
  vscode.extensions.getExtension<YamlExtensionApi>(YAML_EXTENSION_ID);

/** Publish both context keys so exactly one SML menu item is visible. */
async function setSmlContextKeys(): Promise<void> {
  const installed = yamlExtension() !== undefined;
  const enabled = isEnabled();
  await vscode.commands.executeCommand("setContext", CTX_YAML_INSTALLED, installed);
  await vscode.commands.executeCommand("setContext", CTX_SML_ENABLED, enabled);
  log?.debug(`context keys: yamlExtensionInstalled=${installed} smlEnabled=${enabled}`);
}

export function registerSmlSchemas(context: vscode.ExtensionContext): void {
  log = vscode.window.createOutputChannel("AtScale PS-Utils", { log: true });
  context.subscriptions.push(log);

  // ── Everything the menu switch depends on, before any I/O that can fail ──────
  registerSmlCommands(context);
  void setSmlContextKeys();

  context.subscriptions.push(
    vscode.workspace.onDidChangeConfiguration((event) => {
      if (event.affectsConfiguration(FULL_SETTING)) void setSmlContextKeys();
    }),
    vscode.extensions.onDidChange(() => {
      void setSmlContextKeys();
      attemptRegistration();
    }),
  );

  // ── Schema loading. A failure here must not take the switch down with it ─────
  const schemaDir = path.join(context.extensionPath, "media", "sml-schema");
  const schemas = new Map<string, string>();
  // The same schemas, parsed, for the unknown-key linter. The YAML extension wants
  // text and the linter wants objects; parsing once here beats doing it per keystroke.
  const parsedSchemas = new Map<string, JsonSchema>();
  const byDirectory = new Map<string, string>();
  let allowlist = Allowlist.empty();
  let loaded = false;

  try {
    const index = JSON.parse(
      fs.readFileSync(path.join(schemaDir, "index.json"), "utf8"),
    ) as SchemaIndex;

    allowlist = Allowlist.from(index.knownUndocumented ?? []);

    // Schemas are small (~110 KB in total) and `requestSchemaContent` is
    // synchronous, so they are read once up front rather than on every keystroke.
    for (const [objectType, entry] of Object.entries(index.objectTypes)) {
      const text = fs.readFileSync(path.join(schemaDir, entry.schema), "utf8");
      schemas.set(objectType, text);
      parsedSchemas.set(objectType, JSON.parse(text) as JsonSchema);
      // Conventional directory → object type, for files with no `object_type` yet.
      // `models/` maps to both `model` and `composite_model`; first wins, and the
      // content sniff resolves it correctly whenever the key is present.
      if (entry.directory && !byDirectory.has(entry.directory)) {
        byDirectory.set(entry.directory, objectType);
      }
    }
    loaded = true;
    log.info(
      `loaded ${schemas.size} SML schemas from ${schemaDir}` +
        ` (${allowlist.size} known-undocumented keys allowlisted)`,
    );
  } catch (error) {
    log.error(`could not load the SML schemas from ${schemaDir}: ${String(error)}`);
  }

  /** Read `object_type` from an open document, or from disk if it is not open. */
  const sniffObjectType = (uri: vscode.Uri): string | undefined => {
    const open = vscode.workspace.textDocuments.find((d) => d.uri.toString() === uri.toString());
    if (open) {
      return OBJECT_TYPE.exec(open.getText())?.[1];
    }
    if (uri.scheme !== "file") return undefined;
    try {
      const handle = fs.openSync(uri.fsPath, "r");
      try {
        const buffer = Buffer.alloc(SNIFF_BYTES);
        const read = fs.readSync(handle, buffer, 0, SNIFF_BYTES, 0);
        return OBJECT_TYPE.exec(buffer.subarray(0, read).toString("utf8"))?.[1];
      } finally {
        fs.closeSync(handle);
      }
    } catch {
      return undefined;
    }
  };

  /** Fall back to the layout `generate-shared-model-plan/sml-loader.ts` assumes. */
  const objectTypeFromPath = (uri: vscode.Uri): string | undefined => {
    const base = path.basename(uri.path).toLowerCase();
    if (base === "catalog.yml" || base === "catalog.yaml") return "catalog";
    if (base === "packages.yml" || base === "packages.yaml") return "package";
    const parent = path.basename(path.dirname(uri.path)).toLowerCase();
    return byDirectory.get(parent);
  };

  const objectTypeFor = (resource: string): string | undefined => {
    let uri: vscode.Uri;
    try {
      uri = vscode.Uri.parse(resource);
    } catch {
      return undefined;
    }
    if (!/\.ya?ml$/i.test(uri.path)) return undefined;

    const sniffed = sniffObjectType(uri);
    if (sniffed) {
      // An `object_type` we do not recognise means this is not ours (or is from a
      // newer spec) — claim nothing rather than impose the wrong schema.
      return schemas.has(sniffed) ? sniffed : undefined;
    }
    // No `object_type` yet: fall back to the layout. This is the common case while
    // a new file is being typed, which is when completion helps most.
    return objectTypeFromPath(uri);
  };

  let registered = false;

  /**
   * Register the schema contributor, at most once. Re-attempted when the extension
   * list changes, so installing the YAML extension can take effect without a reload
   * where the host allows it.
   */
  function attemptRegistration(): void {
    if (registered || !loaded) return;
    const extension = yamlExtension();
    if (!extension) {
      log?.info(`${YAML_EXTENSION_ID} is not installed; schema support is unavailable`);
      maybePromptForYamlExtension(context, objectTypeFor);
      return;
    }
    registered = true;

    void (async () => {
      try {
        const api = extension.isActive ? extension.exports : await extension.activate();
        api.registerContributor(
          SCHEME,
          (resource) => {
            // Checked per request rather than at registration, so toggling the
            // setting affects every schema resolution from that point on.
            if (!isEnabled()) return undefined;
            const objectType = objectTypeFor(resource);
            return objectType ? `${SCHEME}://schema/${objectType}` : undefined;
          },
          (uri) => schemas.get(uri.replace(`${SCHEME}://schema/`, "")),
        );
        log?.info("registered the SML schema contributor with the YAML extension");
      } catch (error) {
        registered = false;
        log?.error(`could not register the SML schema contributor: ${String(error)}`);
      }
    })();
  }

  attemptRegistration();

  // Unknown-key warnings. Deliberately outside `attemptRegistration`: this channel
  // is the extension's own DiagnosticCollection, so it works whether or not
  // redhat.vscode-yaml is installed. It still needs the schemas, though.
  if (loaded) {
    registerUnknownKeyDiagnostics(context, {
      schemaFor: (objectType) => parsedSchemas.get(objectType),
      objectTypeFor,
      isEnabled,
      allowlist,
      log,
    });
  }
}

/**
 * Write `psUtils.smlEnabled` at workspace scope — the whole point of the toggle is
 * that it applies to this project only.
 */
async function setEnabled(enabled: boolean): Promise<void> {
  log?.info(`SML support toggle: requested ${enabled ? "enable" : "disable"}`);
  const configuration = vscode.workspace.getConfiguration(CONFIG_SECTION);

  const target = vscode.workspace.workspaceFolders?.length
    ? vscode.ConfigurationTarget.Workspace
    : undefined;

  if (target === undefined) {
    // With no folder open there is nowhere project-scoped to write. Offer the
    // global setting rather than failing silently.
    const choice = await vscode.window.showWarningMessage(
      "No project is open, so SML support can only be changed globally.",
      `${enabled ? "Enable" : "Disable"} globally`,
      "Cancel",
    );
    if (choice && choice !== "Cancel") {
      await configuration.update(ENABLED_SETTING, enabled, vscode.ConfigurationTarget.Global);
      await setSmlContextKeys();
    }
    return;
  }

  try {
    await configuration.update(ENABLED_SETTING, enabled, target);
  } catch (error) {
    // Surface it: a silent failure here is indistinguishable from a dead menu item.
    const detail = String(error);
    log?.error(`failed to write ${FULL_SETTING}: ${detail}`);

    if (/not a registered configuration/.test(detail)) {
      // Seen when the extension is updated while VS Code is already running.
      // Extension *code* is re-read when the extension host restarts, so the new
      // build is live and this command runs — but `contributes.configuration` is
      // registered once per *application* session, so the setting itself is still
      // absent from the registry and `update()` refuses it. Reloading the window or
      // opening a new one does not help: every window shares the application's
      // extension scan. Only a full quit and relaunch rebuilds it.
      void vscode.window.showErrorMessage(
        `PS-Utils was updated while VS Code was running, so "${FULL_SETTING}" is not registered yet. ` +
          "Quit VS Code completely and reopen it — reloading the window, or opening a new window, " +
          "is not enough.",
        "Show Log",
      ).then((choice) => {
        if (choice === "Show Log") log?.show();
      });
      return;
    }

    void vscode.window.showErrorMessage(`Could not update ${FULL_SETTING}: ${detail}`);
    return;
  }

  await setSmlContextKeys();
  log?.info(`wrote ${FULL_SETTING}=${enabled} to workspace settings`);

  // The YAML language server resolves a document's schema when the document is
  // opened or changed and then caches that result; it offers no hook to invalidate
  // it. So flipping this setting governs every *subsequent* resolution but leaves
  // editors that are already open showing their previous state — which reads as the
  // toggle having done nothing. Say so, and offer the reload that fixes it.
  const affectsOpenEditors = vscode.workspace.textDocuments.some(
    (document) => document.languageId === "yaml" && !document.isUntitled,
  );

  const message = enabled
    ? "SML support enabled for this project."
    : "SML support disabled for this project.";

  if (!affectsOpenEditors) {
    void vscode.window.showInformationMessage(message);
    return;
  }

  const choice = await vscode.window.showInformationMessage(
    `${message} YAML files already open keep their previous validation until the window reloads.`,
    "Reload Window",
    "Later",
  );
  if (choice === "Reload Window") {
    await vscode.commands.executeCommand("workbench.action.reloadWindow");
  }
}

function registerSmlCommands(context: vscode.ExtensionContext): void {
  context.subscriptions.push(
    // `enable` / `disable` back the ☐ / ☑ checkbox in the Explorer menu: each is
    // shown only in the state where clicking it flips the value.
    vscode.commands.registerCommand("psUtils.sml.enable", () => setEnabled(true)),
    vscode.commands.registerCommand("psUtils.sml.disable", () => setEnabled(false)),
    // The Command Palette entry, where a checkbox glyph would read badly.
    vscode.commands.registerCommand("psUtils.sml.toggle", () => setEnabled(!isEnabled())),
    vscode.commands.registerCommand("psUtils.sml.installYamlExtension", async () => {
      const choice = await vscode.window.showInformationMessage(
        "SML validation, completion and hover documentation need the YAML extension " +
          "(redhat.vscode-yaml), because VS Code has no built-in YAML schema support. " +
          "Syntax highlighting works without it.",
        "Install",
        "View in Marketplace",
        "Cancel",
      );

      if (choice === "Install") {
        try {
          await vscode.commands.executeCommand(
            "workbench.extensions.installExtension",
            YAML_EXTENSION_ID,
          );
          await setSmlContextKeys();
          const reload = await vscode.window.showInformationMessage(
            "YAML extension installed. Reload to activate SML schema support.",
            "Reload Window",
            "Later",
          );
          if (reload === "Reload Window") {
            await vscode.commands.executeCommand("workbench.action.reloadWindow");
          }
        } catch (error) {
          // Most often a restricted or offline host; point at the Marketplace rather
          // than leaving the failure unexplained.
          log?.error(`could not install ${YAML_EXTENSION_ID}: ${String(error)}`);
          void vscode.window.showErrorMessage(
            `Could not install the YAML extension automatically (${String(error)}). ` +
              `Search for "${YAML_EXTENSION_ID}" in the Extensions view.`,
          );
        }
      } else if (choice === "View in Marketplace") {
        await vscode.commands.executeCommand(
          "workbench.extensions.search",
          `@id:${YAML_EXTENSION_ID}`,
        );
      }
    }),
  );
  log?.debug("registered SML commands: enable, disable, toggle, installYamlExtension");
}

/**
 * Offer to install redhat.vscode-yaml, but only once, and only for someone who has
 * actually opened a file this extension recognises as SML. The menu item is the
 * discoverable path; this is the one that finds people who never open the menu.
 */
function maybePromptForYamlExtension(
  context: vscode.ExtensionContext,
  objectTypeFor: (resource: string) => string | undefined,
): void {
  let prompted = false;

  const consider = (document: vscode.TextDocument): void => {
    if (prompted || !isEnabled()) return;
    if (context.globalState.get<boolean>(PROMPT_DISMISSED_KEY)) return;
    if (document.languageId !== "yaml") return;
    if (!objectTypeFor(document.uri.toString())) return;

    prompted = true;
    void vscode.window
      .showInformationMessage(
        "This looks like an SML file. Install the YAML extension to get SML validation, " +
          "completion and hover documentation from PS-Utils.",
        "Install",
        "Not now",
        "Never",
      )
      .then((choice) => {
        if (choice === "Install") {
          void vscode.commands.executeCommand("psUtils.sml.installYamlExtension");
        } else if (choice === "Never") {
          void context.globalState.update(PROMPT_DISMISSED_KEY, true);
        }
        // "Not now" and dismissal leave `prompted` set, so it stays quiet for the
        // rest of the session but returns on the next window.
      });
  };

  context.subscriptions.push(vscode.workspace.onDidOpenTextDocument(consider));
  for (const document of vscode.workspace.textDocuments) consider(document);
}
